NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc

app_bundle:
    resource: "@AppBundle/Resources/config/routing.yml"
    prefix:   /api

app:
    resource: "@AppBundle/Controller/"
    prefix: /api
    type: 'annotation'

auth:
    resource: "@AuthBundle/Controller/"
    prefix:   /
    type: "annotation"