user:
    resource: "@AppBundle/Resources/config/routing/user.yml"

# todo: handle uploader routes like in car-service
oneup_uploader:
    resource: .
    type: uploader
# ------------------------------------------------